<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{94995db9-82fb-4583-94ae-a1fd1a7e3270}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	// Drive
	fbDrive			      : FB_Drive;
	fbDrive_01		      : FB_Drive;
	fbDriveReverse	      : FB_DriveReverse;

	//Drive Control	
	fbMotorControl 	      : FB_MotorControl(fbDrive);
	fbMotorControl_01 	  : FB_MotorControl(fbDrive_01);	
	fbMotorControlReverse : FB_MotorControlReverse(fbDriveReverse);

	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbMotorControl();
fbMotorControl_01();
fbMotorControlReverse();


]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>