<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FermentationProcess" Id="{cd4debd5-e4da-4fbd-a7f2-abb66eea5825}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM FermentationProcess
VAR
	

	//Drive Control	
	fbDriveReverse		          : FB_DriveReverse;
	fbMccRev_001			 	  : FB_MotorControlReverse(fbDriveReverse);
	fbMccRev_002			 	  : FB_MotorControlReverse(fbDriveReverse);
	fbMccRev_003			 	  : FB_MotorControlReverse(fbDriveReverse);
	fbMccRev_004 	 			  : FB_MotorControlReverse(fbDriveReverse);
	fbMccRev_005			 	  : FB_MotorControlReverse(fbDriveReverse);
	fbMccRev_006			 	  : FB_MotorControlReverse(fbDriveReverse);
	fbMccRev_007				  : FB_MotorControlReverse(fbDriveReverse);
	fbMccRev_008 	 			  : FB_MotorControlReverse(fbDriveReverse);
	fbMccRev_009 	  			  : FB_MotorControlReverse(fbDriveReverse);
	fbMccRev_010 	              : FB_MotorControlReverse(fbDriveReverse);
	fbMccRev_011			 	  : FB_MotorControlReverse(fbDriveReverse);
	fbMccRev_012			 	  : FB_MotorControlReverse(fbDriveReverse);
	fbMccRev_013			 	  : FB_MotorControlReverse(fbDriveReverse);
	fbMccRev_014 	 			  : FB_MotorControlReverse(fbDriveReverse);
	fbMccRev_015			 	  : FB_MotorControlReverse(fbDriveReverse);
	fbMccRev_016			 	  : FB_MotorControlReverse(fbDriveReverse);
	fbMccRev_017				  : FB_MotorControlReverse(fbDriveReverse);
	fbMccRev_018 	 			  : FB_MotorControlReverse(fbDriveReverse);
	fbMccRev_019 	  			  : FB_MotorControlReverse(fbDriveReverse);
	fbMccRev_020 	              : FB_MotorControlReverse(fbDriveReverse);
	
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>