<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FermentationProcess_001" Id="{cd4debd5-e4da-4fbd-a7f2-abb66eea5825}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM FermentationProcess_001
VAR
	

	//MCC Driver	
	fbDriveReverse_001		      : FB_DriveReverse;
	fbDriveReverse_002		      : FB_DriveReverse;
	fbDriveReverse_003		      : FB_DriveReverse;
	fbDriveReverse_004		      : FB_DriveReverse;
	fbDriveReverse_005		      : FB_DriveReverse;
	fbDriveReverse_006		      : FB_DriveReverse;
	fbDriveReverse_007		      : FB_DriveReverse;
	fbDriveReverse_008		      : FB_DriveReverse;
	fbDriveReverse_009		      : FB_DriveReverse;
	fbDriveReverse_010		      : FB_DriveReverse;
	fbDriveReverse_011		      : FB_DriveReverse;
	fbDriveReverse_012		      : FB_DriveReverse;
	fbDriveReverse_013		      : FB_DriveReverse;
	fbDriveReverse_014		      : FB_DriveReverse;
	fbDriveReverse_015		      : FB_DriveReverse;
	fbDriveReverse_016		      : FB_DriveReverse;
	fbDriveReverse_017		      : FB_DriveReverse;
	fbDriveReverse_018		      : FB_DriveReverse;
	fbDriveReverse_019		      : FB_DriveReverse;
	fbDriveReverse_020		      : FB_DriveReverse;


	//MCC Driver Control
	fbMccRev_001			 	  : FB_MotorControlReverse(fbDriveReverse_001);
	fbMccRev_002			 	  : FB_MotorControlReverse(fbDriveReverse_002);
	fbMccRev_003			 	  : FB_MotorControlReverse(fbDriveReverse_003);
	fbMccRev_004 	 			  : FB_MotorControlReverse(fbDriveReverse_004);
	fbMccRev_005			 	  : FB_MotorControlReverse(fbDriveReverse_005);
	fbMccRev_006			 	  : FB_MotorControlReverse(fbDriveReverse_006);
	fbMccRev_007				  : FB_MotorControlReverse(fbDriveReverse_007);
	fbMccRev_008 	 			  : FB_MotorControlReverse(fbDriveReverse_008);
	fbMccRev_009 	  			  : FB_MotorControlReverse(fbDriveReverse_009);
	fbMccRev_010 	              : FB_MotorControlReverse(fbDriveReverse_010);
	fbMccRev_011			 	  : FB_MotorControlReverse(fbDriveReverse_011);
	fbMccRev_012			 	  : FB_MotorControlReverse(fbDriveReverse_012);
	fbMccRev_013			 	  : FB_MotorControlReverse(fbDriveReverse_013);
	fbMccRev_014 	 			  : FB_MotorControlReverse(fbDriveReverse_014);
	fbMccRev_015			 	  : FB_MotorControlReverse(fbDriveReverse_015);
	fbMccRev_016			 	  : FB_MotorControlReverse(fbDriveReverse_016);
	fbMccRev_017				  : FB_MotorControlReverse(fbDriveReverse_017);
	fbMccRev_018 	 			  : FB_MotorControlReverse(fbDriveReverse_018);
	fbMccRev_019 	  			  : FB_MotorControlReverse(fbDriveReverse_019);
	fbMccRev_020 	              : FB_MotorControlReverse(fbDriveReverse_020);
	
	//Temperature Sensor
	fbTempSens_001				  : FB_Scaling;
	fbTempSens_002				  : FB_Scaling;
	fbTempSens_003				  : FB_Scaling;
	//Level Sensor
	fbLevelSens_001				  : FB_Scaling;
	//Ph Sensor
	fbPhSens_001				  : FB_Scaling;	
	//Pressure Sensor
	fbPressureSens_001			  : FB_Scaling;	
	
	
	
	
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ACT_Motor();
ACT_TempSens();
ACT_LevelSens();
ACT_PhSens();




]]></ST>
    </Implementation>
    <Action Name="ACT_LevelSens" Id="{8ee61bea-2bee-417e-8d54-d51a566be6b4}">
      <Implementation>
        <CFC>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCImplementationObject">
                <o n="Items" t="CFCItemList">
                  <l2 n="InnerList">
                    <o t="CFCBoxElement">
                      <o n="Inputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCInputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">2L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">3L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">4L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">5L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">6L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Outputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCOutputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">7L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">8L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">9L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Texts" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCText">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rX"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">10L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rXmin"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">11L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rXmax"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">12L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rYmin"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">13L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rYmax"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">14L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_bAlarmHi"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">15L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_bAlarmLo"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">16L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rY"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">17L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"FB_Scaling"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">18L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"fbLevelSens_001"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">19L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Parameters" t="CFCItemList">
                        <l2 n="InnerList" />
                      </o>
                      <n n="PreparedParameters" />
                      <v n="PageArea">0</v>
                      <v n="Bounds">"26, 13, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="EnEno">false</v>
                      <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="Forced">false</v>
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">1L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">21L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"Fermentation_001.LevelSens_001.rRawLevelValue"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">22L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"5, 15, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">20L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">24L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"0"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">25L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"5, 16, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">23L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">27L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"32767"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">28L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"5, 17, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">26L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">30L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"Fermentation_001.LevelSens_001.rLevelValue"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">31L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"38, 17, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">29L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">33L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"0"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">34L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"5, 18, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">32L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">36L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"100"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">37L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"5, 19, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">35L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"1, 1, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">24L</v>
                      <v n="DestPinId">3L</v>
                      <v n="Id">38L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"1, 1, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">27L</v>
                      <v n="DestPinId">4L</v>
                      <v n="Id">39L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"1, 1, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">36L</v>
                      <v n="DestPinId">6L</v>
                      <v n="Id">40L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"1, 1, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">33L</v>
                      <v n="DestPinId">5L</v>
                      <v n="Id">41L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"1, 1, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">21L</v>
                      <v n="DestPinId">2L</v>
                      <v n="Id">42L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"1, 1, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">9L</v>
                      <v n="DestPinId">30L</v>
                      <v n="Id">43L</v>
                    </o>
                  </l2>
                </o>
                <n n="ParameterInitializationMethodGenerator" />
                <o n="RoutingPathTable" t="CFCRoutingPathTable">
                  <d2 n="InnerDictionary" ckt="CFCRoutingConnection" cvt="CFCPointList">
                    <o>
                      <v n="ConnectionId">43L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">36</v>
                        <v n="Y">17</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">36</v>
                          <v n="Y">17</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">37</v>
                          <v n="Y">17</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">42L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">24</v>
                        <v n="Y">15</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">24</v>
                          <v n="Y">15</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">25</v>
                          <v n="Y">15</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">41L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">8</v>
                        <v n="Y">18</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">8</v>
                          <v n="Y">18</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">25</v>
                          <v n="Y">18</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">40L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">9</v>
                        <v n="Y">19</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">9</v>
                          <v n="Y">19</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">25</v>
                          <v n="Y">19</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">39L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">10</v>
                        <v n="Y">17</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">10</v>
                          <v n="Y">17</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">25</v>
                          <v n="Y">17</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">38L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">8</v>
                        <v n="Y">16</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">8</v>
                          <v n="Y">16</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">25</v>
                          <v n="Y">16</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                  </d2>
                </o>
                <v n="AutoSizeCanvas">true</v>
                <v n="CanvasWidth">58</v>
                <v n="CanvasHeight">22</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCBoxElement">{f5becf35-b1f3-4274-b411-81d4b63a1516}</Type>
              <Type n="CFCConnection">{5ae2e111-ecff-4a21-b647-2d4da63f8db7}</Type>
              <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
              <Type n="CFCInputElement">{d51129f5-df27-4886-99d1-c564d2e2c1f6}</Type>
              <Type n="CFCInputPin">{c994f6e0-311a-4a1c-bc38-75fe34892406}</Type>
              <Type n="CFCInputPinWithSetReset">{5c3476a8-05c5-430e-861c-9cfa51d68ca8}</Type>
              <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
              <Type n="CFCOutputElement">{8d9e2b78-3efe-4fe4-8160-f3a7381ddd8f}</Type>
              <Type n="CFCOutputPin">{65582d84-cf18-4ca0-be59-bf5a3d00b8f8}</Type>
              <Type n="CFCPoint">{b3e42b54-b8f2-45d3-825d-747f82f244a0}</Type>
              <Type n="CFCPointList">{584effbc-813e-443a-bf78-ad9c8d49db41}</Type>
              <Type n="CFCRoutingConnection">{93c117eb-0884-403b-b01e-28b89f47e041}</Type>
              <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
              <Type n="CFCText">{72f2b13f-5349-4a8a-bbe6-2bccf3f42179}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="KindOfCall">{77f43dfe-ca6a-4869-828f-7609d8ed6ea6}</Type>
              <Type n="ProcessValueAccess">{88453c7d-d652-4a27-a1b0-a1953be49a5c}</Type>
              <Type n="SetReset">{24449d48-c96a-49c4-b9d1-a4ea34aedce3}</Type>
              <Type n="SetResetRef">{233bc97c-69fe-4d29-b40e-a9a9b854044e}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </CFC>
      </Implementation>
    </Action>
    <Action Name="ACT_Motor" Id="{7e5ca941-1b2f-4bd8-a7e6-7c6d33833563}">
      <Implementation>
        <ST><![CDATA[//Sygnały obiektów MccRev_* mieszadeł fermentora

//***************************************************SCADA********************************************************

//MccRev_001 variable sets by SCADA
FermentationProcess_001.fbMccRev_001.ScadaAutoButton     := Fermentation_001.MccRev_001.bAutoButton;    // SCADA button Auto Command
FermentationProcess_001.fbMccRev_001.ScadaForwardButton  := Fermentation_001.MccRev_001.bForwardButton; // SCADA button Forward Command
FermentationProcess_001.fbMccRev_001.ScadaReverseButton  := Fermentation_001.MccRev_001.bReverseButton; // SCADA button Reverse Command

//MccRev_002 variable sets by SCADA
FermentationProcess_001.fbMccRev_002.ScadaAutoButton     := Fermentation_001.MccRev_002.bAutoButton;    // SCADA button Auto Command
FermentationProcess_001.fbMccRev_002.ScadaForwardButton  := Fermentation_001.MccRev_002.bForwardButton; // SCADA button Forward Command
FermentationProcess_001.fbMccRev_002.ScadaReverseButton  := Fermentation_001.MccRev_002.bReverseButton; // SCADA button Reverse Command

//MccRev_003 variable sets by SCADA
FermentationProcess_001.fbMccRev_003.ScadaAutoButton     := Fermentation_001.MccRev_003.bAutoButton;    // SCADA button Auto Command
FermentationProcess_001.fbMccRev_003.ScadaForwardButton  := Fermentation_001.MccRev_003.bForwardButton; // SCADA button Forward Command
FermentationProcess_001.fbMccRev_003.ScadaReverseButton  := Fermentation_001.MccRev_003.bReverseButton; // SCADA button Reverse Command

//MccRev_004 variable sets by SCADA
FermentationProcess_001.fbMccRev_004.ScadaAutoButton     := Fermentation_001.MccRev_004.bAutoButton;    // SCADA button Auto Command
FermentationProcess_001.fbMccRev_004.ScadaForwardButton  := Fermentation_001.MccRev_004.bForwardButton; // SCADA button Forward Command
FermentationProcess_001.fbMccRev_004.ScadaReverseButton  := Fermentation_001.MccRev_004.bReverseButton; // SCADA button Reverse Command

//MccRev_005 variable sets by SCADA
FermentationProcess_001.fbMccRev_005.ScadaAutoButton     := Fermentation_001.MccRev_005.bAutoButton;    // SCADA button Auto Command
FermentationProcess_001.fbMccRev_005.ScadaForwardButton  := Fermentation_001.MccRev_005.bForwardButton; // SCADA button Forward Command
FermentationProcess_001.fbMccRev_005.ScadaReverseButton  := Fermentation_001.MccRev_005.bReverseButton; // SCADA button Reverse Command

//MccRev_006 variable sets by SCADA
FermentationProcess_001.fbMccRev_006.ScadaAutoButton     := Fermentation_001.MccRev_006.bAutoButton;    // SCADA button Auto Command
FermentationProcess_001.fbMccRev_006.ScadaForwardButton  := Fermentation_001.MccRev_006.bForwardButton; // SCADA button Forward Command
FermentationProcess_001.fbMccRev_006.ScadaReverseButton  := Fermentation_001.MccRev_006.bReverseButton; // SCADA button Reverse Command

//MccRev_007 variable sets by SCADA
FermentationProcess_001.fbMccRev_007.ScadaAutoButton     := Fermentation_001.MccRev_007.bAutoButton;    // SCADA button Auto Command
FermentationProcess_001.fbMccRev_007.ScadaForwardButton  := Fermentation_001.MccRev_007.bForwardButton; // SCADA button Forward Command
FermentationProcess_001.fbMccRev_007.ScadaReverseButton  := Fermentation_001.MccRev_007.bReverseButton; // SCADA button Reverse Command

//MccRev_008 variable sets by SCADA
FermentationProcess_001.fbMccRev_008.ScadaAutoButton     := Fermentation_001.MccRev_008.bAutoButton;    // SCADA button Auto Command
FermentationProcess_001.fbMccRev_008.ScadaForwardButton  := Fermentation_001.MccRev_008.bForwardButton; // SCADA button Forward Command
FermentationProcess_001.fbMccRev_008.ScadaReverseButton  := Fermentation_001.MccRev_008.bReverseButton; // SCADA button Reverse Command

//MccRev_009 variable sets by SCADA
FermentationProcess_001.fbMccRev_009.ScadaAutoButton     := Fermentation_001.MccRev_009.bAutoButton;    // SCADA button Auto Command
FermentationProcess_001.fbMccRev_009.ScadaForwardButton  := Fermentation_001.MccRev_009.bForwardButton; // SCADA button Forward Command
FermentationProcess_001.fbMccRev_009.ScadaReverseButton  := Fermentation_001.MccRev_009.bReverseButton; // SCADA button Reverse Command

//MccRev_010 variable sets by SCADA
FermentationProcess_001.fbMccRev_010.ScadaAutoButton     := Fermentation_001.MccRev_010.bAutoButton;    // SCADA button Auto Command
FermentationProcess_001.fbMccRev_010.ScadaForwardButton  := Fermentation_001.MccRev_010.bForwardButton; // SCADA button Forward Command
FermentationProcess_001.fbMccRev_010.ScadaReverseButton  := Fermentation_001.MccRev_010.bReverseButton; // SCADA button Reverse Command

//MccRev_011 variable sets by SCADA
FermentationProcess_001.fbMccRev_011.ScadaAutoButton     := Fermentation_001.MccRev_011.bAutoButton;    // SCADA button Auto Command
FermentationProcess_001.fbMccRev_011.ScadaForwardButton  := Fermentation_001.MccRev_011.bForwardButton; // SCADA button Forward Command
FermentationProcess_001.fbMccRev_011.ScadaReverseButton  := Fermentation_001.MccRev_011.bReverseButton; // SCADA button Reverse Command

//MccRev_012 variable sets by SCADA
FermentationProcess_001.fbMccRev_012.ScadaAutoButton     := Fermentation_001.MccRev_012.bAutoButton;    // SCADA button Auto Command
FermentationProcess_001.fbMccRev_012.ScadaForwardButton  := Fermentation_001.MccRev_012.bForwardButton; // SCADA button Forward Command
FermentationProcess_001.fbMccRev_012.ScadaReverseButton  := Fermentation_001.MccRev_012.bReverseButton; // SCADA button Reverse Command

//MccRev_013 variable sets by SCADA
FermentationProcess_001.fbMccRev_013.ScadaAutoButton     := Fermentation_001.MccRev_013.bAutoButton;    // SCADA button Auto Command
FermentationProcess_001.fbMccRev_013.ScadaForwardButton  := Fermentation_001.MccRev_013.bForwardButton; // SCADA button Forward Command
FermentationProcess_001.fbMccRev_013.ScadaReverseButton  := Fermentation_001.MccRev_013.bReverseButton; // SCADA button Reverse Command

//MccRev_014 variable sets by SCADA
FermentationProcess_001.fbMccRev_014.ScadaAutoButton     := Fermentation_001.MccRev_014.bAutoButton;    // SCADA button Auto Command
FermentationProcess_001.fbMccRev_014.ScadaForwardButton  := Fermentation_001.MccRev_014.bForwardButton; // SCADA button Forward Command
FermentationProcess_001.fbMccRev_014.ScadaReverseButton  := Fermentation_001.MccRev_014.bReverseButton; // SCADA button Reverse Command

//MccRev_015 variable sets by SCADA
FermentationProcess_001.fbMccRev_015.ScadaAutoButton     := Fermentation_001.MccRev_015.bAutoButton;    // SCADA button Auto Command
FermentationProcess_001.fbMccRev_015.ScadaForwardButton  := Fermentation_001.MccRev_015.bForwardButton; // SCADA button Forward Command
FermentationProcess_001.fbMccRev_015.ScadaReverseButton  := Fermentation_001.MccRev_015.bReverseButton; // SCADA button Reverse Command

//MccRev_016 variable sets by SCADA
FermentationProcess_001.fbMccRev_016.ScadaAutoButton     := Fermentation_001.MccRev_016.bAutoButton;    // SCADA button Auto Command
FermentationProcess_001.fbMccRev_016.ScadaForwardButton  := Fermentation_001.MccRev_016.bForwardButton; // SCADA button Forward Command
FermentationProcess_001.fbMccRev_016.ScadaReverseButton  := Fermentation_001.MccRev_016.bReverseButton; // SCADA button Reverse Command

//MccRev_017 variable sets by SCADA
FermentationProcess_001.fbMccRev_017.ScadaAutoButton     := Fermentation_001.MccRev_017.bAutoButton;    // SCADA button Auto Command
FermentationProcess_001.fbMccRev_017.ScadaForwardButton  := Fermentation_001.MccRev_017.bForwardButton; // SCADA button Forward Command
FermentationProcess_001.fbMccRev_017.ScadaReverseButton  := Fermentation_001.MccRev_017.bReverseButton; // SCADA button Reverse Command

//MccRev_018 variable sets by SCADA
FermentationProcess_001.fbMccRev_018.ScadaAutoButton     := Fermentation_001.MccRev_018.bAutoButton;    // SCADA button Auto Command
FermentationProcess_001.fbMccRev_018.ScadaForwardButton  := Fermentation_001.MccRev_018.bForwardButton; // SCADA button Forward Command
FermentationProcess_001.fbMccRev_018.ScadaReverseButton  := Fermentation_001.MccRev_018.bReverseButton; // SCADA button Reverse Command

//MccRev_019 variable sets by SCADA
FermentationProcess_001.fbMccRev_019.ScadaAutoButton     := Fermentation_001.MccRev_019.bAutoButton;    // SCADA button Auto Command
FermentationProcess_001.fbMccRev_019.ScadaForwardButton  := Fermentation_001.MccRev_019.bForwardButton; // SCADA button Forward Command
FermentationProcess_001.fbMccRev_019.ScadaReverseButton  := Fermentation_001.MccRev_019.bReverseButton; // SCADA button Reverse Command

//MccRev_020 variable sets by SCADA
FermentationProcess_001.fbMccRev_020.ScadaAutoButton     := Fermentation_001.MccRev_020.bAutoButton;    // SCADA button Auto Command
FermentationProcess_001.fbMccRev_020.ScadaForwardButton  := Fermentation_001.MccRev_020.bForwardButton; // SCADA button Forward Command
FermentationProcess_001.fbMccRev_020.ScadaReverseButton  := Fermentation_001.MccRev_020.bReverseButton; // SCADA button Reverse Command


//***************************************************PLC********************************************************************


//MccRev_001 variable sets by PLC
FermentationProcess_001.fbDriveReverse_001.MotorProtection := Fermentation_001.MccRev_001.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_001.bContactor     := FermentationProcess_001.fbDriveReverse_001.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_001.udHours        := FermentationProcess_001.fbDriveReverse_001.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_001.uMinutes       := FermentationProcess_001.fbDriveReverse_001.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_001.uSeconds       := FermentationProcess_001.fbDriveReverse_001.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_001.sState         := FermentationProcess_001.fbDriveReverse_001.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_001.sStatus        := FermentationProcess_001.fbDriveReverse_001.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_002 variable sets by PLC
FermentationProcess_001.fbDriveReverse_002.MotorProtection := Fermentation_001.MccRev_002.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_002.bContactor     := FermentationProcess_001.fbDriveReverse_002.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_002.udHours        := FermentationProcess_001.fbDriveReverse_002.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_002.uMinutes       := FermentationProcess_001.fbDriveReverse_002.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_002.uSeconds       := FermentationProcess_001.fbDriveReverse_002.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_002.sState         := FermentationProcess_001.fbDriveReverse_002.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_002.sStatus        := FermentationProcess_001.fbDriveReverse_002.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register

//MccRev_003 variable sets by PLC
FermentationProcess_001.fbDriveReverse_003.MotorProtection :=Fermentation_001.MccRev_003.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_003.bContactor     := FermentationProcess_001.fbDriveReverse_003.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_003.udHours        := FermentationProcess_001.fbDriveReverse_003.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_003.uMinutes       := FermentationProcess_001.fbDriveReverse_003.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_003.uSeconds       := FermentationProcess_001.fbDriveReverse_003.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_003.sState         := FermentationProcess_001.fbDriveReverse_003.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_003.sStatus        := FermentationProcess_001.fbDriveReverse_003.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register

//MccRev_004 variable sets by PLC
FermentationProcess_001.fbDriveReverse_004.MotorProtection := Fermentation_001.MccRev_004.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_004.bContactor     := FermentationProcess_001.fbDriveReverse_004.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_004.udHours        := FermentationProcess_001.fbDriveReverse_004.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_004.uMinutes       := FermentationProcess_001.fbDriveReverse_004.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_004.uSeconds       := FermentationProcess_001.fbDriveReverse_004.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_004.sState         := FermentationProcess_001.fbDriveReverse_004.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_004.sStatus        := FermentationProcess_001.fbDriveReverse_004.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_005 variable sets by PLC
FermentationProcess_001.fbDriveReverse_005.MotorProtection := Fermentation_001.MccRev_005.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_005.bContactor     := FermentationProcess_001.fbDriveReverse_005.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_005.udHours        := FermentationProcess_001.fbDriveReverse_005.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_005.uMinutes       := FermentationProcess_001.fbDriveReverse_005.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_005.uSeconds       := FermentationProcess_001.fbDriveReverse_005.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_005.sState         := FermentationProcess_001.fbDriveReverse_005.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_005.sStatus        := FermentationProcess_001.fbDriveReverse_005.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_006 variable sets by PLC
FermentationProcess_001.fbDriveReverse_006.MotorProtection := Fermentation_001.MccRev_006.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_006.bContactor     := FermentationProcess_001.fbDriveReverse_006.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_006.udHours        := FermentationProcess_001.fbDriveReverse_006.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_006.uMinutes       := FermentationProcess_001.fbDriveReverse_006.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_006.uSeconds       := FermentationProcess_001.fbDriveReverse_006.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_006.sState         := FermentationProcess_001.fbDriveReverse_006.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_006.sStatus        := FermentationProcess_001.fbDriveReverse_006.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register

//MccRev_007 variable sets by PLC
FermentationProcess_001.fbDriveReverse_007.MotorProtection := Fermentation_001.MccRev_007.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_007.bContactor     := FermentationProcess_001.fbDriveReverse_007.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_007.udHours        := FermentationProcess_001.fbDriveReverse_007.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_007.uMinutes       := FermentationProcess_001.fbDriveReverse_007.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_007.uSeconds       := FermentationProcess_001.fbDriveReverse_007.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_007.sState         := FermentationProcess_001.fbDriveReverse_007.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_007.sStatus        := FermentationProcess_001.fbDriveReverse_007.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register

//MccRev_008 variable sets by PLC
FermentationProcess_001.fbDriveReverse_008.MotorProtection := Fermentation_001.MccRev_008.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_008.bContactor     := FermentationProcess_001.fbDriveReverse_008.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_008.udHours        := FermentationProcess_001.fbDriveReverse_008.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_008.uMinutes       := FermentationProcess_001.fbDriveReverse_008.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_008.uSeconds       := FermentationProcess_001.fbDriveReverse_008.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_008.sState         := FermentationProcess_001.fbDriveReverse_008.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_008.sStatus        := FermentationProcess_001.fbDriveReverse_008.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_009 variable sets by PLC
FermentationProcess_001.fbDriveReverse_009.MotorProtection := Fermentation_001.MccRev_009.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_009.bContactor     := FermentationProcess_001.fbDriveReverse_009.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_009.udHours        := FermentationProcess_001.fbDriveReverse_009.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_009.uMinutes       := FermentationProcess_001.fbDriveReverse_009.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_009.uSeconds       := FermentationProcess_001.fbDriveReverse_009.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_009.sState         := FermentationProcess_001.fbDriveReverse_009.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_009.sStatus        := FermentationProcess_001.fbDriveReverse_009.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register

//MccRev_010 variable sets by PLC
FermentationProcess_001.fbDriveReverse_010.MotorProtection := Fermentation_001.MccRev_010.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_010.bContactor     := FermentationProcess_001.fbDriveReverse_010.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_010.udHours        := FermentationProcess_001.fbDriveReverse_010.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_010.uMinutes       := FermentationProcess_001.fbDriveReverse_010.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_010.uSeconds       := FermentationProcess_001.fbDriveReverse_010.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_010.sState         := FermentationProcess_001.fbDriveReverse_010.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_010.sStatus        := FermentationProcess_001.fbDriveReverse_010.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register

//MccRev_011 variable sets by PLC
FermentationProcess_001.fbDriveReverse_011.MotorProtection := Fermentation_001.MccRev_011.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_011.bContactor     := FermentationProcess_001.fbDriveReverse_011.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_011.udHours        := FermentationProcess_001.fbDriveReverse_011.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_011.uMinutes       := FermentationProcess_001.fbDriveReverse_011.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_011.uSeconds       := FermentationProcess_001.fbDriveReverse_011.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_011.sState         := FermentationProcess_001.fbDriveReverse_011.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_011.sStatus        := FermentationProcess_001.fbDriveReverse_011.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_012 variable sets by PLC
FermentationProcess_001.fbDriveReverse_012.MotorProtection := Fermentation_001.MccRev_012.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_012.bContactor     := FermentationProcess_001.fbDriveReverse_012.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_012.udHours        := FermentationProcess_001.fbDriveReverse_012.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_012.uMinutes       := FermentationProcess_001.fbDriveReverse_012.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_012.uSeconds       := FermentationProcess_001.fbDriveReverse_012.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_012.sState         := FermentationProcess_001.fbDriveReverse_012.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_012.sStatus        := FermentationProcess_001.fbDriveReverse_012.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_013 variable sets by PLC
FermentationProcess_001.fbDriveReverse_013.MotorProtection := Fermentation_001.MccRev_013.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_013.bContactor     := FermentationProcess_001.fbDriveReverse_013.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_013.udHours        := FermentationProcess_001.fbDriveReverse_013.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_013.uMinutes       := FermentationProcess_001.fbDriveReverse_013.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_013.uSeconds       := FermentationProcess_001.fbDriveReverse_013.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_013.sState         := FermentationProcess_001.fbDriveReverse_013.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_013.sStatus        := FermentationProcess_001.fbDriveReverse_013.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_014 variable sets by PLC
FermentationProcess_001.fbDriveReverse_014.MotorProtection := Fermentation_001.MccRev_014.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_014.bContactor     := FermentationProcess_001.fbDriveReverse_014.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_014.udHours        := FermentationProcess_001.fbDriveReverse_014.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_014.uMinutes       := FermentationProcess_001.fbDriveReverse_014.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_014.uSeconds       := FermentationProcess_001.fbDriveReverse_014.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_014.sState         := FermentationProcess_001.fbDriveReverse_014.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_014.sStatus        := FermentationProcess_001.fbDriveReverse_014.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register

//MccRev_015 variable sets by PLC
FermentationProcess_001.fbDriveReverse_015.MotorProtection := Fermentation_001.MccRev_015.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_015.bContactor     := FermentationProcess_001.fbDriveReverse_015.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_015.udHours        := FermentationProcess_001.fbDriveReverse_015.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_015.uMinutes       := FermentationProcess_001.fbDriveReverse_015.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_015.uSeconds       := FermentationProcess_001.fbDriveReverse_015.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_015.sState         := FermentationProcess_001.fbDriveReverse_015.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_015.sStatus        := FermentationProcess_001.fbDriveReverse_015.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_016 variable sets by PLC
FermentationProcess_001.fbDriveReverse_016.MotorProtection := Fermentation_001.MccRev_016.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_016.bContactor     := FermentationProcess_001.fbDriveReverse_016.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_016.udHours        := FermentationProcess_001.fbDriveReverse_016.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_016.uMinutes       := FermentationProcess_001.fbDriveReverse_016.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_016.uSeconds       := FermentationProcess_001.fbDriveReverse_016.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_016.sState         := FermentationProcess_001.fbDriveReverse_016.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_016.sStatus        := FermentationProcess_001.fbDriveReverse_016.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_017 variable sets by PLC
FermentationProcess_001.fbDriveReverse_017.MotorProtection := Fermentation_001.MccRev_017.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_017.bContactor     := FermentationProcess_001.fbDriveReverse_017.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_017.udHours        := FermentationProcess_001.fbDriveReverse_017.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_017.uMinutes       := FermentationProcess_001.fbDriveReverse_017.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_017.uSeconds       := FermentationProcess_001.fbDriveReverse_017.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_017.sState         := FermentationProcess_001.fbDriveReverse_017.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_017.sStatus        := FermentationProcess_001.fbDriveReverse_017.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_018 variable sets by PLC
FermentationProcess_001.fbDriveReverse_018.MotorProtection := Fermentation_001.MccRev_018.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_018.bContactor     := FermentationProcess_001.fbDriveReverse_018.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_018.udHours        := FermentationProcess_001.fbDriveReverse_018.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_018.uMinutes       := FermentationProcess_001.fbDriveReverse_018.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_018.uSeconds       := FermentationProcess_001.fbDriveReverse_018.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_018.sState         := FermentationProcess_001.fbDriveReverse_018.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_018.sStatus        := FermentationProcess_001.fbDriveReverse_018.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_019 variable sets by PLC
FermentationProcess_001.fbDriveReverse_019.MotorProtection := Fermentation_001.MccRev_019.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_019.bContactor     := FermentationProcess_001.fbDriveReverse_019.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_019.udHours        := FermentationProcess_001.fbDriveReverse_019.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_019.uMinutes       := FermentationProcess_001.fbDriveReverse_019.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_019.uSeconds       := FermentationProcess_001.fbDriveReverse_019.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_019.sState         := FermentationProcess_001.fbDriveReverse_019.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_019.sStatus        := FermentationProcess_001.fbDriveReverse_019.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_020 variable sets by PLC
FermentationProcess_001.fbDriveReverse_020.MotorProtection := Fermentation_001.MccRev_020.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_020.bContactor     := FermentationProcess_001.fbDriveReverse_020.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_020.udHours        := FermentationProcess_001.fbDriveReverse_020.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_020.uMinutes       := FermentationProcess_001.fbDriveReverse_020.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_020.uSeconds       := FermentationProcess_001.fbDriveReverse_020.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_020.sState         := FermentationProcess_001.fbDriveReverse_020.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_020.sStatus        := FermentationProcess_001.fbDriveReverse_020.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register
]]></ST>
      </Implementation>
    </Action>
    <Action Name="ACT_PhSens" Id="{c132ae7c-f82a-406c-b89d-8bb7114273eb}">
      <Implementation>
        <CFC>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCImplementationObject">
                <o n="Items" t="CFCItemList">
                  <l2 n="InnerList">
                    <o t="CFCBoxElement">
                      <o n="Inputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCInputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">2L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">3L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">4L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">5L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">6L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Outputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCOutputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">7L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">8L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">9L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Texts" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCText">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rX"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">10L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rXmin"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">11L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rXmax"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">12L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rYmin"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">13L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rYmax"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">14L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_bAlarmHi"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">15L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_bAlarmLo"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">16L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rY"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">17L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"FB_Scaling"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">18L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"fbPhSens_001"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">19L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Parameters" t="CFCItemList">
                        <l2 n="InnerList" />
                      </o>
                      <n n="PreparedParameters" />
                      <v n="PageArea">0</v>
                      <v n="Bounds">"26, 13, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="EnEno">false</v>
                      <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="Forced">false</v>
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">1L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">21L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"Fermentation_001.PhSens_001.rRawPhValue"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">22L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"5, 15, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">20L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">24L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"0"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">25L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"5, 16, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">23L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">27L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"32767"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">28L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"5, 17, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">26L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">30L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"Fermentation_001.PhSens_001.rPhValue"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">31L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"38, 17, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">29L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">33L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"0"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">34L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"5, 18, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">32L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">36L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"12"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">37L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"5, 19, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">35L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"1, 1, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">24L</v>
                      <v n="DestPinId">3L</v>
                      <v n="Id">38L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"1, 1, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">27L</v>
                      <v n="DestPinId">4L</v>
                      <v n="Id">39L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"1, 1, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">36L</v>
                      <v n="DestPinId">6L</v>
                      <v n="Id">40L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"1, 1, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">33L</v>
                      <v n="DestPinId">5L</v>
                      <v n="Id">41L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"1, 1, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">21L</v>
                      <v n="DestPinId">2L</v>
                      <v n="Id">42L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"1, 1, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">9L</v>
                      <v n="DestPinId">30L</v>
                      <v n="Id">43L</v>
                    </o>
                  </l2>
                </o>
                <n n="ParameterInitializationMethodGenerator" />
                <o n="RoutingPathTable" t="CFCRoutingPathTable">
                  <d2 n="InnerDictionary" ckt="CFCRoutingConnection" cvt="CFCPointList">
                    <o>
                      <v n="ConnectionId">38L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">8</v>
                        <v n="Y">16</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">8</v>
                          <v n="Y">16</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">25</v>
                          <v n="Y">16</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">39L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">10</v>
                        <v n="Y">17</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">10</v>
                          <v n="Y">17</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">25</v>
                          <v n="Y">17</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">40L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">9</v>
                        <v n="Y">19</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">9</v>
                          <v n="Y">19</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">25</v>
                          <v n="Y">19</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">41L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">8</v>
                        <v n="Y">18</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">8</v>
                          <v n="Y">18</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">25</v>
                          <v n="Y">18</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">42L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">22</v>
                        <v n="Y">15</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">22</v>
                          <v n="Y">15</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">25</v>
                          <v n="Y">15</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">43L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">36</v>
                        <v n="Y">17</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">36</v>
                          <v n="Y">17</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">100</v>
                        </o>
                        <o>
                          <v n="X">37</v>
                          <v n="Y">17</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                  </d2>
                </o>
                <v n="AutoSizeCanvas">true</v>
                <v n="CanvasWidth">56</v>
                <v n="CanvasHeight">22</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCBoxElement">{f5becf35-b1f3-4274-b411-81d4b63a1516}</Type>
              <Type n="CFCConnection">{5ae2e111-ecff-4a21-b647-2d4da63f8db7}</Type>
              <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
              <Type n="CFCInputElement">{d51129f5-df27-4886-99d1-c564d2e2c1f6}</Type>
              <Type n="CFCInputPin">{c994f6e0-311a-4a1c-bc38-75fe34892406}</Type>
              <Type n="CFCInputPinWithSetReset">{5c3476a8-05c5-430e-861c-9cfa51d68ca8}</Type>
              <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
              <Type n="CFCOutputElement">{8d9e2b78-3efe-4fe4-8160-f3a7381ddd8f}</Type>
              <Type n="CFCOutputPin">{65582d84-cf18-4ca0-be59-bf5a3d00b8f8}</Type>
              <Type n="CFCPoint">{b3e42b54-b8f2-45d3-825d-747f82f244a0}</Type>
              <Type n="CFCPointList">{584effbc-813e-443a-bf78-ad9c8d49db41}</Type>
              <Type n="CFCRoutingConnection">{93c117eb-0884-403b-b01e-28b89f47e041}</Type>
              <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
              <Type n="CFCText">{72f2b13f-5349-4a8a-bbe6-2bccf3f42179}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="KindOfCall">{77f43dfe-ca6a-4869-828f-7609d8ed6ea6}</Type>
              <Type n="ProcessValueAccess">{88453c7d-d652-4a27-a1b0-a1953be49a5c}</Type>
              <Type n="SetReset">{24449d48-c96a-49c4-b9d1-a4ea34aedce3}</Type>
              <Type n="SetResetRef">{233bc97c-69fe-4d29-b40e-a9a9b854044e}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </CFC>
      </Implementation>
    </Action>
    <Action Name="ACT_PressureSens" Id="{6ccb0a22-bf81-4ede-881e-cab4baf9ffd0}">
      <Implementation>
        <CFC>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCImplementationObject">
                <o n="Items" t="CFCItemList">
                  <l2 n="InnerList">
                    <o t="CFCBoxElement">
                      <o n="Inputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCInputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">2L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">3L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">4L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">5L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">6L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Outputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCOutputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">7L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">8L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">9L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Texts" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCText">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rX"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">10L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rXmin"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">11L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rXmax"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">12L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rYmin"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">13L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rYmax"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">14L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_bAlarmHi"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">15L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_bAlarmLo"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">16L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rY"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">17L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"FB_Scaling"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">18L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"fbPressureSens_001"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">19L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Parameters" t="CFCItemList">
                        <l2 n="InnerList" />
                      </o>
                      <n n="PreparedParameters" />
                      <v n="PageArea">0</v>
                      <v n="Bounds">"26, 13, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="EnEno">false</v>
                      <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="Forced">false</v>
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">1L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">21L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"Fermentation_001.PhSens_001.rRawPhValue"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">22L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"5, 15, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">20L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">24L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"0"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">25L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"5, 16, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">23L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">27L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"32767"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">28L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"5, 17, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">26L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">30L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"Fermentation_001.PhSens_001.rPhValue"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">31L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"38, 17, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">29L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">33L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"0"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">34L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"5, 18, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">32L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">36L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"12"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">37L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"5, 19, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">35L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"1, 1, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">24L</v>
                      <v n="DestPinId">3L</v>
                      <v n="Id">38L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"1, 1, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">27L</v>
                      <v n="DestPinId">4L</v>
                      <v n="Id">39L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"1, 1, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">36L</v>
                      <v n="DestPinId">6L</v>
                      <v n="Id">40L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"1, 1, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">33L</v>
                      <v n="DestPinId">5L</v>
                      <v n="Id">41L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"1, 1, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">21L</v>
                      <v n="DestPinId">2L</v>
                      <v n="Id">42L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"1, 1, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">9L</v>
                      <v n="DestPinId">30L</v>
                      <v n="Id">43L</v>
                    </o>
                  </l2>
                </o>
                <n n="ParameterInitializationMethodGenerator" />
                <o n="RoutingPathTable" t="CFCRoutingPathTable">
                  <d2 n="InnerDictionary" ckt="CFCRoutingConnection" cvt="CFCPointList">
                    <o>
                      <v n="ConnectionId">43L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">36</v>
                        <v n="Y">17</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">36</v>
                          <v n="Y">17</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">100</v>
                        </o>
                        <o>
                          <v n="X">37</v>
                          <v n="Y">17</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">42L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">22</v>
                        <v n="Y">15</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">22</v>
                          <v n="Y">15</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">25</v>
                          <v n="Y">15</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">41L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">8</v>
                        <v n="Y">18</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">8</v>
                          <v n="Y">18</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">25</v>
                          <v n="Y">18</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">40L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">9</v>
                        <v n="Y">19</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">9</v>
                          <v n="Y">19</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">25</v>
                          <v n="Y">19</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">39L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">10</v>
                        <v n="Y">17</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">10</v>
                          <v n="Y">17</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">25</v>
                          <v n="Y">17</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">38L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">8</v>
                        <v n="Y">16</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">8</v>
                          <v n="Y">16</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">25</v>
                          <v n="Y">16</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                  </d2>
                </o>
                <v n="AutoSizeCanvas">true</v>
                <v n="CanvasWidth">56</v>
                <v n="CanvasHeight">22</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCBoxElement">{f5becf35-b1f3-4274-b411-81d4b63a1516}</Type>
              <Type n="CFCConnection">{5ae2e111-ecff-4a21-b647-2d4da63f8db7}</Type>
              <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
              <Type n="CFCInputElement">{d51129f5-df27-4886-99d1-c564d2e2c1f6}</Type>
              <Type n="CFCInputPin">{c994f6e0-311a-4a1c-bc38-75fe34892406}</Type>
              <Type n="CFCInputPinWithSetReset">{5c3476a8-05c5-430e-861c-9cfa51d68ca8}</Type>
              <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
              <Type n="CFCOutputElement">{8d9e2b78-3efe-4fe4-8160-f3a7381ddd8f}</Type>
              <Type n="CFCOutputPin">{65582d84-cf18-4ca0-be59-bf5a3d00b8f8}</Type>
              <Type n="CFCPoint">{b3e42b54-b8f2-45d3-825d-747f82f244a0}</Type>
              <Type n="CFCPointList">{584effbc-813e-443a-bf78-ad9c8d49db41}</Type>
              <Type n="CFCRoutingConnection">{93c117eb-0884-403b-b01e-28b89f47e041}</Type>
              <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
              <Type n="CFCText">{72f2b13f-5349-4a8a-bbe6-2bccf3f42179}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="KindOfCall">{77f43dfe-ca6a-4869-828f-7609d8ed6ea6}</Type>
              <Type n="ProcessValueAccess">{88453c7d-d652-4a27-a1b0-a1953be49a5c}</Type>
              <Type n="SetReset">{24449d48-c96a-49c4-b9d1-a4ea34aedce3}</Type>
              <Type n="SetResetRef">{233bc97c-69fe-4d29-b40e-a9a9b854044e}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </CFC>
      </Implementation>
    </Action>
    <Action Name="ACT_TempSens" Id="{1c3023f9-db11-40ae-aa02-b0cabd6dbc52}">
      <Implementation>
        <CFC>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCImplementationObject">
                <o n="Items" t="CFCItemList">
                  <l2 n="InnerList">
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">52L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"32767"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">53L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 18, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">51L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">56L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"0"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">57L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 19, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">55L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">59L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"100"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">60L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 20, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">58L</v>
                    </o>
                    <o t="CFCBoxElement">
                      <o n="Inputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCInputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">126L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">127L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">128L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">129L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">130L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Outputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCOutputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">131L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">132L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">133L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Texts" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCText">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rX"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">134L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rXmin"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">135L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rXmax"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">136L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rYmin"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">137L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rYmax"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">138L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_bAlarmHi"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">139L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_bAlarmLo"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">140L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rY"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">141L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"FB_Scaling"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">142L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"fbTempSens_003"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">143L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Parameters" t="CFCItemList">
                        <l2 n="InnerList" />
                      </o>
                      <n n="PreparedParameters" />
                      <v n="PageArea">0</v>
                      <v n="Bounds">"24, 24, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="EnEno">false</v>
                      <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="Forced">false</v>
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">125L</v>
                    </o>
                    <o t="CFCBoxElement">
                      <o n="Inputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCInputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">83L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">84L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">85L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">86L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">87L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Outputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCOutputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">88L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">89L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">90L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Texts" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCText">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rX"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">91L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rXmin"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">92L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rXmax"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">93L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rYmin"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">94L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rYmax"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">95L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_bAlarmHi"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">96L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_bAlarmLo"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">97L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rY"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">98L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"FB_Scaling"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">99L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"fbTempSens_001"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">100L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Parameters" t="CFCItemList">
                        <l2 n="InnerList" />
                      </o>
                      <n n="PreparedParameters" />
                      <v n="PageArea">0</v>
                      <v n="Bounds">"24, 2, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="EnEno">false</v>
                      <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="Forced">false</v>
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">82L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">145L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"Fermentation_001.TempSens_003.rRawTempValue"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">146L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 26, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">144L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">151L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"0"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">152L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 27, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">150L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">102L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"Fermentation_001.TempSens_001.rRawTempValue"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">103L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 4, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">101L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">117L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"32767"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">118L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 28, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">116L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">108L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"0"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">109L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 5, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">107L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">148L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"Fermentation_001.TempSens_003.rTempValue"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">149L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"36, 28, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">147L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">120L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"0"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">121L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 29, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">119L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">74L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"32767"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">75L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 6, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">73L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">105L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"Fermentation_001.TempSens_001.rTempValue"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">106L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"36, 6, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">104L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">123L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"100"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">124L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 30, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">122L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">77L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"0"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">78L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 7, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">76L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">80L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"100"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">81L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 8, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">79L</v>
                    </o>
                    <o t="CFCBoxElement">
                      <o n="Inputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCInputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">27L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">29L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">31L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">33L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">35L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Outputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCOutputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">37L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">39L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">41L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Texts" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCText">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rX"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">28L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rXmin"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">30L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rXmax"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">32L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rYmin"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">34L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rYmax"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">36L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_bAlarmHi"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">38L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_bAlarmLo"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">40L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rY"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">42L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"FB_Scaling"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">25L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"fbTempSens_002"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">26L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Parameters" t="CFCItemList">
                        <l2 n="InnerList" />
                      </o>
                      <n n="PreparedParameters" />
                      <v n="PageArea">0</v>
                      <v n="Bounds">"24, 14, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="EnEno">false</v>
                      <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="Forced">false</v>
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">18L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">44L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"Fermentation_001.TempSens_002.rRawTempValue"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">45L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 16, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">43L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">64L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"Fermentation_001.TempSens_002.rTempValue"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">65L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"36, 18, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">63L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">48L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"0"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">49L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 17, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">47L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">48L</v>
                      <v n="DestPinId">29L</v>
                      <v n="Id">50L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">52L</v>
                      <v n="DestPinId">31L</v>
                      <v n="Id">54L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">59L</v>
                      <v n="DestPinId">35L</v>
                      <v n="Id">61L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">56L</v>
                      <v n="DestPinId">33L</v>
                      <v n="Id">62L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">44L</v>
                      <v n="DestPinId">27L</v>
                      <v n="Id">67L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">41L</v>
                      <v n="DestPinId">64L</v>
                      <v n="Id">72L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"-2, -13, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">108L</v>
                      <v n="DestPinId">84L</v>
                      <v n="Id">110L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"-2, -13, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">74L</v>
                      <v n="DestPinId">85L</v>
                      <v n="Id">111L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"-2, -13, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">80L</v>
                      <v n="DestPinId">87L</v>
                      <v n="Id">112L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"-2, -13, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">77L</v>
                      <v n="DestPinId">86L</v>
                      <v n="Id">113L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"-2, -13, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">102L</v>
                      <v n="DestPinId">83L</v>
                      <v n="Id">114L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"-2, -13, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">90L</v>
                      <v n="DestPinId">105L</v>
                      <v n="Id">115L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"-2, -13, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">151L</v>
                      <v n="DestPinId">127L</v>
                      <v n="Id">153L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"-2, -13, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">117L</v>
                      <v n="DestPinId">128L</v>
                      <v n="Id">154L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"-2, -13, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">123L</v>
                      <v n="DestPinId">130L</v>
                      <v n="Id">155L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"-2, -13, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">120L</v>
                      <v n="DestPinId">129L</v>
                      <v n="Id">156L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"-2, -13, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">145L</v>
                      <v n="DestPinId">126L</v>
                      <v n="Id">157L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"-2, -13, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">133L</v>
                      <v n="DestPinId">148L</v>
                      <v n="Id">158L</v>
                    </o>
                  </l2>
                </o>
                <n n="ParameterInitializationMethodGenerator" />
                <o n="RoutingPathTable" t="CFCRoutingPathTable">
                  <d2 n="InnerDictionary" ckt="CFCRoutingConnection" cvt="CFCPointList">
                    <o>
                      <v n="ConnectionId">50L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">6</v>
                        <v n="Y">17</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">6</v>
                          <v n="Y">17</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">23</v>
                          <v n="Y">17</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">157L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">22</v>
                        <v n="Y">26</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">22</v>
                          <v n="Y">26</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">23</v>
                          <v n="Y">26</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">158L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">34</v>
                        <v n="Y">28</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">34</v>
                          <v n="Y">28</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">35</v>
                          <v n="Y">28</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">153L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">6</v>
                        <v n="Y">27</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">6</v>
                          <v n="Y">27</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">23</v>
                          <v n="Y">27</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">154L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">8</v>
                        <v n="Y">28</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">8</v>
                          <v n="Y">28</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">23</v>
                          <v n="Y">28</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">115L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">34</v>
                        <v n="Y">6</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">34</v>
                          <v n="Y">6</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">35</v>
                          <v n="Y">6</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">114L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">22</v>
                        <v n="Y">4</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">22</v>
                          <v n="Y">4</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">23</v>
                          <v n="Y">4</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">113L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">6</v>
                        <v n="Y">7</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">6</v>
                          <v n="Y">7</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">23</v>
                          <v n="Y">7</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">112L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">7</v>
                        <v n="Y">8</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">7</v>
                          <v n="Y">8</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">23</v>
                          <v n="Y">8</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">111L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">8</v>
                        <v n="Y">6</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">8</v>
                          <v n="Y">6</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">23</v>
                          <v n="Y">6</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">110L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">6</v>
                        <v n="Y">5</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">6</v>
                          <v n="Y">5</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">23</v>
                          <v n="Y">5</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">62L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">6</v>
                        <v n="Y">19</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">6</v>
                          <v n="Y">19</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">23</v>
                          <v n="Y">19</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">67L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">22</v>
                        <v n="Y">16</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">22</v>
                          <v n="Y">16</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">23</v>
                          <v n="Y">16</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">72L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">34</v>
                        <v n="Y">18</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">34</v>
                          <v n="Y">18</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">35</v>
                          <v n="Y">18</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">61L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">7</v>
                        <v n="Y">20</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">7</v>
                          <v n="Y">20</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">23</v>
                          <v n="Y">20</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">54L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">8</v>
                        <v n="Y">18</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">8</v>
                          <v n="Y">18</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">23</v>
                          <v n="Y">18</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">156L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">6</v>
                        <v n="Y">29</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">6</v>
                          <v n="Y">29</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">23</v>
                          <v n="Y">29</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">155L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">7</v>
                        <v n="Y">30</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">7</v>
                          <v n="Y">30</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">23</v>
                          <v n="Y">30</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                  </d2>
                </o>
                <v n="AutoSizeCanvas">true</v>
                <v n="CanvasWidth">56</v>
                <v n="CanvasHeight">33</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCBoxElement">{f5becf35-b1f3-4274-b411-81d4b63a1516}</Type>
              <Type n="CFCConnection">{5ae2e111-ecff-4a21-b647-2d4da63f8db7}</Type>
              <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
              <Type n="CFCInputElement">{d51129f5-df27-4886-99d1-c564d2e2c1f6}</Type>
              <Type n="CFCInputPin">{c994f6e0-311a-4a1c-bc38-75fe34892406}</Type>
              <Type n="CFCInputPinWithSetReset">{5c3476a8-05c5-430e-861c-9cfa51d68ca8}</Type>
              <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
              <Type n="CFCOutputElement">{8d9e2b78-3efe-4fe4-8160-f3a7381ddd8f}</Type>
              <Type n="CFCOutputPin">{65582d84-cf18-4ca0-be59-bf5a3d00b8f8}</Type>
              <Type n="CFCPoint">{b3e42b54-b8f2-45d3-825d-747f82f244a0}</Type>
              <Type n="CFCPointList">{584effbc-813e-443a-bf78-ad9c8d49db41}</Type>
              <Type n="CFCRoutingConnection">{93c117eb-0884-403b-b01e-28b89f47e041}</Type>
              <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
              <Type n="CFCText">{72f2b13f-5349-4a8a-bbe6-2bccf3f42179}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="KindOfCall">{77f43dfe-ca6a-4869-828f-7609d8ed6ea6}</Type>
              <Type n="ProcessValueAccess">{88453c7d-d652-4a27-a1b0-a1953be49a5c}</Type>
              <Type n="SetReset">{24449d48-c96a-49c4-b9d1-a4ea34aedce3}</Type>
              <Type n="SetResetRef">{233bc97c-69fe-4d29-b40e-a9a9b854044e}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </CFC>
      </Implementation>
    </Action>
  </POU>
</TcPlcObject>