<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FermentationProcess" Id="{cd4debd5-e4da-4fbd-a7f2-abb66eea5825}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM FermentationProcess
VAR
	

	//MCC Driver	
	fbDriveReverse_001		      : FB_DriveReverse;
	fbDriveReverse_002		      : FB_DriveReverse;
	fbDriveReverse_003		      : FB_DriveReverse;
	fbDriveReverse_004		      : FB_DriveReverse;
	fbDriveReverse_005		      : FB_DriveReverse;
	fbDriveReverse_006		      : FB_DriveReverse;
	fbDriveReverse_007		      : FB_DriveReverse;
	fbDriveReverse_008		      : FB_DriveReverse;
	fbDriveReverse_009		      : FB_DriveReverse;
	fbDriveReverse_010		      : FB_DriveReverse;
	fbDriveReverse_011		      : FB_DriveReverse;
	fbDriveReverse_012		      : FB_DriveReverse;
	fbDriveReverse_013		      : FB_DriveReverse;
	fbDriveReverse_014		      : FB_DriveReverse;
	fbDriveReverse_015		      : FB_DriveReverse;
	fbDriveReverse_016		      : FB_DriveReverse;
	fbDriveReverse_017		      : FB_DriveReverse;
	fbDriveReverse_018		      : FB_DriveReverse;
	fbDriveReverse_019		      : FB_DriveReverse;
	fbDriveReverse_020		      : FB_DriveReverse;


	//MCC Driver Control
	fbMccRev_001			 	  : FB_MotorControlReverse(fbDriveReverse_001);
	fbMccRev_002			 	  : FB_MotorControlReverse(fbDriveReverse_002);
	fbMccRev_003			 	  : FB_MotorControlReverse(fbDriveReverse_003);
	fbMccRev_004 	 			  : FB_MotorControlReverse(fbDriveReverse_004);
	fbMccRev_005			 	  : FB_MotorControlReverse(fbDriveReverse_005);
	fbMccRev_006			 	  : FB_MotorControlReverse(fbDriveReverse_006);
	fbMccRev_007				  : FB_MotorControlReverse(fbDriveReverse_007);
	fbMccRev_008 	 			  : FB_MotorControlReverse(fbDriveReverse_008);
	fbMccRev_009 	  			  : FB_MotorControlReverse(fbDriveReverse_009);
	fbMccRev_010 	              : FB_MotorControlReverse(fbDriveReverse_010);
	fbMccRev_011			 	  : FB_MotorControlReverse(fbDriveReverse_011);
	fbMccRev_012			 	  : FB_MotorControlReverse(fbDriveReverse_012);
	fbMccRev_013			 	  : FB_MotorControlReverse(fbDriveReverse_013);
	fbMccRev_014 	 			  : FB_MotorControlReverse(fbDriveReverse_014);
	fbMccRev_015			 	  : FB_MotorControlReverse(fbDriveReverse_015);
	fbMccRev_016			 	  : FB_MotorControlReverse(fbDriveReverse_016);
	fbMccRev_017				  : FB_MotorControlReverse(fbDriveReverse_017);
	fbMccRev_018 	 			  : FB_MotorControlReverse(fbDriveReverse_018);
	fbMccRev_019 	  			  : FB_MotorControlReverse(fbDriveReverse_019);
	fbMccRev_020 	              : FB_MotorControlReverse(fbDriveReverse_020);
	
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>