<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FermentationProcess" Id="{cd4debd5-e4da-4fbd-a7f2-abb66eea5825}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM FermentationProcess
VAR
	

	//MCC Driver	
	fbDriveReverse_001		      : FB_DriveReverse;
	fbDriveReverse_002		      : FB_DriveReverse;
	fbDriveReverse_003		      : FB_DriveReverse;
	fbDriveReverse_004		      : FB_DriveReverse;
	fbDriveReverse_005		      : FB_DriveReverse;
	fbDriveReverse_006		      : FB_DriveReverse;
	fbDriveReverse_007		      : FB_DriveReverse;
	fbDriveReverse_008		      : FB_DriveReverse;
	fbDriveReverse_009		      : FB_DriveReverse;
	fbDriveReverse_010		      : FB_DriveReverse;
	fbDriveReverse_011		      : FB_DriveReverse;
	fbDriveReverse_012		      : FB_DriveReverse;
	fbDriveReverse_013		      : FB_DriveReverse;
	fbDriveReverse_014		      : FB_DriveReverse;
	fbDriveReverse_015		      : FB_DriveReverse;
	fbDriveReverse_016		      : FB_DriveReverse;
	fbDriveReverse_017		      : FB_DriveReverse;
	fbDriveReverse_018		      : FB_DriveReverse;
	fbDriveReverse_019		      : FB_DriveReverse;
	fbDriveReverse_020		      : FB_DriveReverse;


	//MCC Driver Control
	fbMccRev_001			 	  : FB_MotorControlReverse(fbDriveReverse_001);
	fbMccRev_002			 	  : FB_MotorControlReverse(fbDriveReverse_002);
	fbMccRev_003			 	  : FB_MotorControlReverse(fbDriveReverse_003);
	fbMccRev_004 	 			  : FB_MotorControlReverse(fbDriveReverse_004);
	fbMccRev_005			 	  : FB_MotorControlReverse(fbDriveReverse_005);
	fbMccRev_006			 	  : FB_MotorControlReverse(fbDriveReverse_006);
	fbMccRev_007				  : FB_MotorControlReverse(fbDriveReverse_007);
	fbMccRev_008 	 			  : FB_MotorControlReverse(fbDriveReverse_008);
	fbMccRev_009 	  			  : FB_MotorControlReverse(fbDriveReverse_009);
	fbMccRev_010 	              : FB_MotorControlReverse(fbDriveReverse_010);
	fbMccRev_011			 	  : FB_MotorControlReverse(fbDriveReverse_011);
	fbMccRev_012			 	  : FB_MotorControlReverse(fbDriveReverse_012);
	fbMccRev_013			 	  : FB_MotorControlReverse(fbDriveReverse_013);
	fbMccRev_014 	 			  : FB_MotorControlReverse(fbDriveReverse_014);
	fbMccRev_015			 	  : FB_MotorControlReverse(fbDriveReverse_015);
	fbMccRev_016			 	  : FB_MotorControlReverse(fbDriveReverse_016);
	fbMccRev_017				  : FB_MotorControlReverse(fbDriveReverse_017);
	fbMccRev_018 	 			  : FB_MotorControlReverse(fbDriveReverse_018);
	fbMccRev_019 	  			  : FB_MotorControlReverse(fbDriveReverse_019);
	fbMccRev_020 	              : FB_MotorControlReverse(fbDriveReverse_020);
	
	//Temperature Sensor
	fbTempSens_001				  : FB_Scaling;
	
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ACT_IO();
ACT_TempSens();



]]></ST>
    </Implementation>
    <Action Name="ACT_IO" Id="{7e5ca941-1b2f-4bd8-a7e6-7c6d33833563}">
      <Implementation>
        <ST><![CDATA[//Sygnały obiektów MccRev_* mieszadeł fermentora

//***************************************************SCADA********************************************************

//MccRev_001 variable sets by SCADA
FermentationProcess.fbMccRev_001.ScadaAutoButton     := Fermentation_001.MccRev_001.bAutoButton;    // SCADA button Auto Command
FermentationProcess.fbMccRev_001.ScadaForwardButton  := Fermentation_001.MccRev_001.bForwardButton; // SCADA button Forward Command
FermentationProcess.fbMccRev_001.ScadaReverseButton  := Fermentation_001.MccRev_001.bReverseButton; // SCADA button Reverse Command

//MccRev_002 variable sets by SCADA
FermentationProcess.fbMccRev_002.ScadaAutoButton     := Fermentation_001.MccRev_002.bAutoButton;    // SCADA button Auto Command
FermentationProcess.fbMccRev_002.ScadaForwardButton  := Fermentation_001.MccRev_002.bForwardButton; // SCADA button Forward Command
FermentationProcess.fbMccRev_002.ScadaReverseButton  := Fermentation_001.MccRev_002.bReverseButton; // SCADA button Reverse Command

//MccRev_003 variable sets by SCADA
FermentationProcess.fbMccRev_003.ScadaAutoButton     := Fermentation_001.MccRev_003.bAutoButton;    // SCADA button Auto Command
FermentationProcess.fbMccRev_003.ScadaForwardButton  := Fermentation_001.MccRev_003.bForwardButton; // SCADA button Forward Command
FermentationProcess.fbMccRev_003.ScadaReverseButton  := Fermentation_001.MccRev_003.bReverseButton; // SCADA button Reverse Command

//MccRev_004 variable sets by SCADA
FermentationProcess.fbMccRev_004.ScadaAutoButton     := Fermentation_001.MccRev_004.bAutoButton;    // SCADA button Auto Command
FermentationProcess.fbMccRev_004.ScadaForwardButton  := Fermentation_001.MccRev_004.bForwardButton; // SCADA button Forward Command
FermentationProcess.fbMccRev_004.ScadaReverseButton  := Fermentation_001.MccRev_004.bReverseButton; // SCADA button Reverse Command

//MccRev_005 variable sets by SCADA
FermentationProcess.fbMccRev_005.ScadaAutoButton     := Fermentation_001.MccRev_005.bAutoButton;    // SCADA button Auto Command
FermentationProcess.fbMccRev_005.ScadaForwardButton  := Fermentation_001.MccRev_005.bForwardButton; // SCADA button Forward Command
FermentationProcess.fbMccRev_005.ScadaReverseButton  := Fermentation_001.MccRev_005.bReverseButton; // SCADA button Reverse Command

//MccRev_006 variable sets by SCADA
FermentationProcess.fbMccRev_006.ScadaAutoButton     := Fermentation_001.MccRev_006.bAutoButton;    // SCADA button Auto Command
FermentationProcess.fbMccRev_006.ScadaForwardButton  := Fermentation_001.MccRev_006.bForwardButton; // SCADA button Forward Command
FermentationProcess.fbMccRev_006.ScadaReverseButton  := Fermentation_001.MccRev_006.bReverseButton; // SCADA button Reverse Command

//MccRev_007 variable sets by SCADA
FermentationProcess.fbMccRev_007.ScadaAutoButton     := Fermentation_001.MccRev_007.bAutoButton;    // SCADA button Auto Command
FermentationProcess.fbMccRev_007.ScadaForwardButton  := Fermentation_001.MccRev_007.bForwardButton; // SCADA button Forward Command
FermentationProcess.fbMccRev_007.ScadaReverseButton  := Fermentation_001.MccRev_007.bReverseButton; // SCADA button Reverse Command

//MccRev_008 variable sets by SCADA
FermentationProcess.fbMccRev_008.ScadaAutoButton     := Fermentation_001.MccRev_008.bAutoButton;    // SCADA button Auto Command
FermentationProcess.fbMccRev_008.ScadaForwardButton  := Fermentation_001.MccRev_008.bForwardButton; // SCADA button Forward Command
FermentationProcess.fbMccRev_008.ScadaReverseButton  := Fermentation_001.MccRev_008.bReverseButton; // SCADA button Reverse Command

//MccRev_009 variable sets by SCADA
FermentationProcess.fbMccRev_009.ScadaAutoButton     := Fermentation_001.MccRev_009.bAutoButton;    // SCADA button Auto Command
FermentationProcess.fbMccRev_009.ScadaForwardButton  := Fermentation_001.MccRev_009.bForwardButton; // SCADA button Forward Command
FermentationProcess.fbMccRev_009.ScadaReverseButton  := Fermentation_001.MccRev_009.bReverseButton; // SCADA button Reverse Command

//MccRev_010 variable sets by SCADA
FermentationProcess.fbMccRev_010.ScadaAutoButton     := Fermentation_001.MccRev_010.bAutoButton;    // SCADA button Auto Command
FermentationProcess.fbMccRev_010.ScadaForwardButton  := Fermentation_001.MccRev_010.bForwardButton; // SCADA button Forward Command
FermentationProcess.fbMccRev_010.ScadaReverseButton  := Fermentation_001.MccRev_010.bReverseButton; // SCADA button Reverse Command

//MccRev_011 variable sets by SCADA
FermentationProcess.fbMccRev_011.ScadaAutoButton     := Fermentation_001.MccRev_011.bAutoButton;    // SCADA button Auto Command
FermentationProcess.fbMccRev_011.ScadaForwardButton  := Fermentation_001.MccRev_011.bForwardButton; // SCADA button Forward Command
FermentationProcess.fbMccRev_011.ScadaReverseButton  := Fermentation_001.MccRev_011.bReverseButton; // SCADA button Reverse Command

//MccRev_012 variable sets by SCADA
FermentationProcess.fbMccRev_012.ScadaAutoButton     := Fermentation_001.MccRev_012.bAutoButton;    // SCADA button Auto Command
FermentationProcess.fbMccRev_012.ScadaForwardButton  := Fermentation_001.MccRev_012.bForwardButton; // SCADA button Forward Command
FermentationProcess.fbMccRev_012.ScadaReverseButton  := Fermentation_001.MccRev_012.bReverseButton; // SCADA button Reverse Command

//MccRev_013 variable sets by SCADA
FermentationProcess.fbMccRev_013.ScadaAutoButton     := Fermentation_001.MccRev_013.bAutoButton;    // SCADA button Auto Command
FermentationProcess.fbMccRev_013.ScadaForwardButton  := Fermentation_001.MccRev_013.bForwardButton; // SCADA button Forward Command
FermentationProcess.fbMccRev_013.ScadaReverseButton  := Fermentation_001.MccRev_013.bReverseButton; // SCADA button Reverse Command

//MccRev_014 variable sets by SCADA
FermentationProcess.fbMccRev_014.ScadaAutoButton     := Fermentation_001.MccRev_014.bAutoButton;    // SCADA button Auto Command
FermentationProcess.fbMccRev_014.ScadaForwardButton  := Fermentation_001.MccRev_014.bForwardButton; // SCADA button Forward Command
FermentationProcess.fbMccRev_014.ScadaReverseButton  := Fermentation_001.MccRev_014.bReverseButton; // SCADA button Reverse Command

//MccRev_015 variable sets by SCADA
FermentationProcess.fbMccRev_015.ScadaAutoButton     := Fermentation_001.MccRev_015.bAutoButton;    // SCADA button Auto Command
FermentationProcess.fbMccRev_015.ScadaForwardButton  := Fermentation_001.MccRev_015.bForwardButton; // SCADA button Forward Command
FermentationProcess.fbMccRev_015.ScadaReverseButton  := Fermentation_001.MccRev_015.bReverseButton; // SCADA button Reverse Command

//MccRev_016 variable sets by SCADA
FermentationProcess.fbMccRev_016.ScadaAutoButton     := Fermentation_001.MccRev_016.bAutoButton;    // SCADA button Auto Command
FermentationProcess.fbMccRev_016.ScadaForwardButton  := Fermentation_001.MccRev_016.bForwardButton; // SCADA button Forward Command
FermentationProcess.fbMccRev_016.ScadaReverseButton  := Fermentation_001.MccRev_016.bReverseButton; // SCADA button Reverse Command

//MccRev_017 variable sets by SCADA
FermentationProcess.fbMccRev_017.ScadaAutoButton     := Fermentation_001.MccRev_017.bAutoButton;    // SCADA button Auto Command
FermentationProcess.fbMccRev_017.ScadaForwardButton  := Fermentation_001.MccRev_017.bForwardButton; // SCADA button Forward Command
FermentationProcess.fbMccRev_017.ScadaReverseButton  := Fermentation_001.MccRev_017.bReverseButton; // SCADA button Reverse Command

//MccRev_018 variable sets by SCADA
FermentationProcess.fbMccRev_018.ScadaAutoButton     := Fermentation_001.MccRev_018.bAutoButton;    // SCADA button Auto Command
FermentationProcess.fbMccRev_018.ScadaForwardButton  := Fermentation_001.MccRev_018.bForwardButton; // SCADA button Forward Command
FermentationProcess.fbMccRev_018.ScadaReverseButton  := Fermentation_001.MccRev_018.bReverseButton; // SCADA button Reverse Command

//MccRev_019 variable sets by SCADA
FermentationProcess.fbMccRev_019.ScadaAutoButton     := Fermentation_001.MccRev_019.bAutoButton;    // SCADA button Auto Command
FermentationProcess.fbMccRev_019.ScadaForwardButton  := Fermentation_001.MccRev_019.bForwardButton; // SCADA button Forward Command
FermentationProcess.fbMccRev_019.ScadaReverseButton  := Fermentation_001.MccRev_019.bReverseButton; // SCADA button Reverse Command

//MccRev_020 variable sets by SCADA
FermentationProcess.fbMccRev_020.ScadaAutoButton     := Fermentation_001.MccRev_020.bAutoButton;    // SCADA button Auto Command
FermentationProcess.fbMccRev_020.ScadaForwardButton  := Fermentation_001.MccRev_020.bForwardButton; // SCADA button Forward Command
FermentationProcess.fbMccRev_020.ScadaReverseButton  := Fermentation_001.MccRev_020.bReverseButton; // SCADA button Reverse Command


//***************************************************PLC********************************************************************


//MccRev_001 variable sets by PLC
FermentationProcess.fbDriveReverse_001.MotorProtection := Fermentation_001.MccRev_001.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_001.bContactor     := FermentationProcess.fbDriveReverse_001.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_001.udHours        := FermentationProcess.fbDriveReverse_001.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_001.uMinutes       := FermentationProcess.fbDriveReverse_001.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_001.uSeconds       := FermentationProcess.fbDriveReverse_001.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_001.sState         := FermentationProcess.fbDriveReverse_001.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_001.sStatus        := FermentationProcess.fbDriveReverse_001.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_002 variable sets by PLC
FermentationProcess.fbDriveReverse_002.MotorProtection := Fermentation_001.MccRev_002.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_002.bContactor     := FermentationProcess.fbDriveReverse_002.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_002.udHours        := FermentationProcess.fbDriveReverse_002.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_002.uMinutes       := FermentationProcess.fbDriveReverse_002.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_002.uSeconds       := FermentationProcess.fbDriveReverse_002.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_002.sState         := FermentationProcess.fbDriveReverse_002.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_002.sStatus        := FermentationProcess.fbDriveReverse_002.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register

//MccRev_003 variable sets by PLC
FermentationProcess.fbDriveReverse_003.MotorProtection :=Fermentation_001.MccRev_003.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_003.bContactor     := FermentationProcess.fbDriveReverse_003.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_003.udHours        := FermentationProcess.fbDriveReverse_003.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_003.uMinutes       := FermentationProcess.fbDriveReverse_003.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_003.uSeconds       := FermentationProcess.fbDriveReverse_003.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_003.sState         := FermentationProcess.fbDriveReverse_003.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_003.sStatus        := FermentationProcess.fbDriveReverse_003.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register

//MccRev_004 variable sets by PLC
FermentationProcess.fbDriveReverse_004.MotorProtection := Fermentation_001.MccRev_004.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_004.bContactor     := FermentationProcess.fbDriveReverse_004.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_004.udHours        := FermentationProcess.fbDriveReverse_004.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_004.uMinutes       := FermentationProcess.fbDriveReverse_004.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_004.uSeconds       := FermentationProcess.fbDriveReverse_004.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_004.sState         := FermentationProcess.fbDriveReverse_004.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_004.sStatus        := FermentationProcess.fbDriveReverse_004.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_005 variable sets by PLC
FermentationProcess.fbDriveReverse_005.MotorProtection := Fermentation_001.MccRev_005.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_005.bContactor     := FermentationProcess.fbDriveReverse_005.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_005.udHours        := FermentationProcess.fbDriveReverse_005.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_005.uMinutes       := FermentationProcess.fbDriveReverse_005.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_005.uSeconds       := FermentationProcess.fbDriveReverse_005.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_005.sState         := FermentationProcess.fbDriveReverse_005.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_005.sStatus        := FermentationProcess.fbDriveReverse_005.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_006 variable sets by PLC
FermentationProcess.fbDriveReverse_006.MotorProtection := Fermentation_001.MccRev_006.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_006.bContactor     := FermentationProcess.fbDriveReverse_006.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_006.udHours        := FermentationProcess.fbDriveReverse_006.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_006.uMinutes       := FermentationProcess.fbDriveReverse_006.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_006.uSeconds       := FermentationProcess.fbDriveReverse_006.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_006.sState         := FermentationProcess.fbDriveReverse_006.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_006.sStatus        := FermentationProcess.fbDriveReverse_006.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register

//MccRev_007 variable sets by PLC
FermentationProcess.fbDriveReverse_007.MotorProtection := Fermentation_001.MccRev_007.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_007.bContactor     := FermentationProcess.fbDriveReverse_007.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_007.udHours        := FermentationProcess.fbDriveReverse_007.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_007.uMinutes       := FermentationProcess.fbDriveReverse_007.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_007.uSeconds       := FermentationProcess.fbDriveReverse_007.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_007.sState         := FermentationProcess.fbDriveReverse_007.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_007.sStatus        := FermentationProcess.fbDriveReverse_007.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register

//MccRev_008 variable sets by PLC
FermentationProcess.fbDriveReverse_008.MotorProtection := Fermentation_001.MccRev_008.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_008.bContactor     := FermentationProcess.fbDriveReverse_008.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_008.udHours        := FermentationProcess.fbDriveReverse_008.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_008.uMinutes       := FermentationProcess.fbDriveReverse_008.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_008.uSeconds       := FermentationProcess.fbDriveReverse_008.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_008.sState         := FermentationProcess.fbDriveReverse_008.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_008.sStatus        := FermentationProcess.fbDriveReverse_008.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_009 variable sets by PLC
FermentationProcess.fbDriveReverse_009.MotorProtection := Fermentation_001.MccRev_009.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_009.bContactor     := FermentationProcess.fbDriveReverse_009.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_009.udHours        := FermentationProcess.fbDriveReverse_009.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_009.uMinutes       := FermentationProcess.fbDriveReverse_009.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_009.uSeconds       := FermentationProcess.fbDriveReverse_009.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_009.sState         := FermentationProcess.fbDriveReverse_009.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_009.sStatus        := FermentationProcess.fbDriveReverse_009.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register

//MccRev_010 variable sets by PLC
FermentationProcess.fbDriveReverse_010.MotorProtection := Fermentation_001.MccRev_010.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_010.bContactor     := FermentationProcess.fbDriveReverse_010.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_010.udHours        := FermentationProcess.fbDriveReverse_010.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_010.uMinutes       := FermentationProcess.fbDriveReverse_010.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_010.uSeconds       := FermentationProcess.fbDriveReverse_010.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_010.sState         := FermentationProcess.fbDriveReverse_010.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_010.sStatus        := FermentationProcess.fbDriveReverse_010.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register

//MccRev_011 variable sets by PLC
FermentationProcess.fbDriveReverse_011.MotorProtection := Fermentation_001.MccRev_011.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_011.bContactor     := FermentationProcess.fbDriveReverse_011.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_011.udHours        := FermentationProcess.fbDriveReverse_011.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_011.uMinutes       := FermentationProcess.fbDriveReverse_011.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_011.uSeconds       := FermentationProcess.fbDriveReverse_011.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_011.sState         := FermentationProcess.fbDriveReverse_011.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_011.sStatus        := FermentationProcess.fbDriveReverse_011.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_012 variable sets by PLC
FermentationProcess.fbDriveReverse_012.MotorProtection := Fermentation_001.MccRev_012.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_012.bContactor     := FermentationProcess.fbDriveReverse_012.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_012.udHours        := FermentationProcess.fbDriveReverse_012.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_012.uMinutes       := FermentationProcess.fbDriveReverse_012.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_012.uSeconds       := FermentationProcess.fbDriveReverse_012.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_012.sState         := FermentationProcess.fbDriveReverse_012.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_012.sStatus        := FermentationProcess.fbDriveReverse_012.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_013 variable sets by PLC
FermentationProcess.fbDriveReverse_013.MotorProtection := Fermentation_001.MccRev_013.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_013.bContactor     := FermentationProcess.fbDriveReverse_013.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_013.udHours        := FermentationProcess.fbDriveReverse_013.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_013.uMinutes       := FermentationProcess.fbDriveReverse_013.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_013.uSeconds       := FermentationProcess.fbDriveReverse_013.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_013.sState         := FermentationProcess.fbDriveReverse_013.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_013.sStatus        := FermentationProcess.fbDriveReverse_013.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_014 variable sets by PLC
FermentationProcess.fbDriveReverse_014.MotorProtection := Fermentation_001.MccRev_014.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_014.bContactor     := FermentationProcess.fbDriveReverse_014.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_014.udHours        := FermentationProcess.fbDriveReverse_014.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_014.uMinutes       := FermentationProcess.fbDriveReverse_014.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_014.uSeconds       := FermentationProcess.fbDriveReverse_014.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_014.sState         := FermentationProcess.fbDriveReverse_014.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_014.sStatus        := FermentationProcess.fbDriveReverse_014.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register

//MccRev_015 variable sets by PLC
FermentationProcess.fbDriveReverse_015.MotorProtection := Fermentation_001.MccRev_015.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_015.bContactor     := FermentationProcess.fbDriveReverse_015.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_015.udHours        := FermentationProcess.fbDriveReverse_015.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_015.uMinutes       := FermentationProcess.fbDriveReverse_015.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_015.uSeconds       := FermentationProcess.fbDriveReverse_015.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_015.sState         := FermentationProcess.fbDriveReverse_015.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_015.sStatus        := FermentationProcess.fbDriveReverse_015.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_016 variable sets by PLC
FermentationProcess.fbDriveReverse_016.MotorProtection := Fermentation_001.MccRev_016.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_016.bContactor     := FermentationProcess.fbDriveReverse_016.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_016.udHours        := FermentationProcess.fbDriveReverse_016.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_016.uMinutes       := FermentationProcess.fbDriveReverse_016.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_016.uSeconds       := FermentationProcess.fbDriveReverse_016.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_016.sState         := FermentationProcess.fbDriveReverse_016.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_016.sStatus        := FermentationProcess.fbDriveReverse_016.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_017 variable sets by PLC
FermentationProcess.fbDriveReverse_017.MotorProtection := Fermentation_001.MccRev_017.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_017.bContactor     := FermentationProcess.fbDriveReverse_017.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_017.udHours        := FermentationProcess.fbDriveReverse_017.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_017.uMinutes       := FermentationProcess.fbDriveReverse_017.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_017.uSeconds       := FermentationProcess.fbDriveReverse_017.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_017.sState         := FermentationProcess.fbDriveReverse_017.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_017.sStatus        := FermentationProcess.fbDriveReverse_017.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_018 variable sets by PLC
FermentationProcess.fbDriveReverse_018.MotorProtection := Fermentation_001.MccRev_018.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_018.bContactor     := FermentationProcess.fbDriveReverse_018.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_018.udHours        := FermentationProcess.fbDriveReverse_018.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_018.uMinutes       := FermentationProcess.fbDriveReverse_018.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_018.uSeconds       := FermentationProcess.fbDriveReverse_018.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_018.sState         := FermentationProcess.fbDriveReverse_018.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_018.sStatus        := FermentationProcess.fbDriveReverse_018.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_019 variable sets by PLC
FermentationProcess.fbDriveReverse_019.MotorProtection := Fermentation_001.MccRev_019.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_019.bContactor     := FermentationProcess.fbDriveReverse_019.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_019.udHours        := FermentationProcess.fbDriveReverse_019.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_019.uMinutes       := FermentationProcess.fbDriveReverse_019.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_019.uSeconds       := FermentationProcess.fbDriveReverse_019.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_019.sState         := FermentationProcess.fbDriveReverse_019.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_019.sStatus        := FermentationProcess.fbDriveReverse_019.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register


//MccRev_020 variable sets by PLC
FermentationProcess.fbDriveReverse_020.MotorProtection := Fermentation_001.MccRev_020.bTermFuse;       // PLC input thermal fuse
Fermentation_001.MccRev_020.bContactor     := FermentationProcess.fbDriveReverse_020.MotorContactor;   // PLC output contactor
Fermentation_001.MccRev_020.udHours        := FermentationProcess.fbDriveReverse_020.Hours;            // PLC Work Time Counter - hours nonvolatile memory register
Fermentation_001.MccRev_020.uMinutes       := FermentationProcess.fbDriveReverse_020.Minuts;           // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_020.uSeconds       := FermentationProcess.fbDriveReverse_020.Seconds;          // PLC Work Time Counter - seconds nonvolatile memory register
Fermentation_001.MccRev_020.sState         := FermentationProcess.fbDriveReverse_020.MotorState;       // PLC Work Time Counter - minutes nonvolatile memory register
Fermentation_001.MccRev_020.sStatus        := FermentationProcess.fbDriveReverse_020.MotorStatus;      // PLC Work Time Counter - seconds nonvolatile memory register
]]></ST>
      </Implementation>
    </Action>
    <Action Name="ACT_TempSens" Id="{1c3023f9-db11-40ae-aa02-b0cabd6dbc52}">
      <Implementation>
        <CFC>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCImplementationObject">
                <o n="Items" t="CFCItemList">
                  <l2 n="InnerList">
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">52L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"32767"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">53L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 18, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">51L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">56L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"0"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">57L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 19, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">55L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">59L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"100"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">60L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 20, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">58L</v>
                    </o>
                    <o t="CFCBoxElement">
                      <o n="Inputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCInputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">27L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">29L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">31L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">33L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">35L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Outputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCOutputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">37L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">39L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">41L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Texts" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCText">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rX"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">28L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rXmin"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">30L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rXmax"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">32L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rYmin"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">34L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rYmax"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">36L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_bAlarmHi"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">38L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_bAlarmLo"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">40L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rY"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">42L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"FB_Scaling"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">25L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"fbTempSens_001"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">26L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Parameters" t="CFCItemList">
                        <l2 n="InnerList" />
                      </o>
                      <n n="PreparedParameters" />
                      <v n="PageArea">0</v>
                      <v n="Bounds">"24, 14, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="EnEno">false</v>
                      <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="Forced">false</v>
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">18L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">44L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"Fermentation_001.TempSens_001.rRawTempValue"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">45L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 16, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">43L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">64L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"Fermentation_001.TempSens_001.rTempValue"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">65L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"36, 18, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">63L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">48L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"0"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">49L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 17, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">47L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">48L</v>
                      <v n="DestPinId">29L</v>
                      <v n="Id">50L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">52L</v>
                      <v n="DestPinId">31L</v>
                      <v n="Id">54L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">59L</v>
                      <v n="DestPinId">35L</v>
                      <v n="Id">61L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">56L</v>
                      <v n="DestPinId">33L</v>
                      <v n="Id">62L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">44L</v>
                      <v n="DestPinId">27L</v>
                      <v n="Id">67L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">41L</v>
                      <v n="DestPinId">64L</v>
                      <v n="Id">72L</v>
                    </o>
                  </l2>
                </o>
                <n n="ParameterInitializationMethodGenerator" />
                <o n="RoutingPathTable" t="CFCRoutingPathTable">
                  <d2 n="InnerDictionary" ckt="CFCRoutingConnection" cvt="CFCPointList">
                    <o>
                      <v n="ConnectionId">50L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">6</v>
                        <v n="Y">17</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">6</v>
                          <v n="Y">17</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">23</v>
                          <v n="Y">17</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">54L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">8</v>
                        <v n="Y">18</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">8</v>
                          <v n="Y">18</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">23</v>
                          <v n="Y">18</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">61L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">7</v>
                        <v n="Y">20</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">7</v>
                          <v n="Y">20</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">23</v>
                          <v n="Y">20</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">72L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">34</v>
                        <v n="Y">18</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">34</v>
                          <v n="Y">18</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">100</v>
                        </o>
                        <o>
                          <v n="X">35</v>
                          <v n="Y">18</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">67L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">22</v>
                        <v n="Y">16</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">22</v>
                          <v n="Y">16</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">23</v>
                          <v n="Y">16</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">62L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">6</v>
                        <v n="Y">19</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">6</v>
                          <v n="Y">19</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">23</v>
                          <v n="Y">19</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                  </d2>
                </o>
                <v n="AutoSizeCanvas">true</v>
                <v n="CanvasWidth">56</v>
                <v n="CanvasHeight">23</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCBoxElement">{f5becf35-b1f3-4274-b411-81d4b63a1516}</Type>
              <Type n="CFCConnection">{5ae2e111-ecff-4a21-b647-2d4da63f8db7}</Type>
              <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
              <Type n="CFCInputElement">{d51129f5-df27-4886-99d1-c564d2e2c1f6}</Type>
              <Type n="CFCInputPin">{c994f6e0-311a-4a1c-bc38-75fe34892406}</Type>
              <Type n="CFCInputPinWithSetReset">{5c3476a8-05c5-430e-861c-9cfa51d68ca8}</Type>
              <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
              <Type n="CFCOutputElement">{8d9e2b78-3efe-4fe4-8160-f3a7381ddd8f}</Type>
              <Type n="CFCOutputPin">{65582d84-cf18-4ca0-be59-bf5a3d00b8f8}</Type>
              <Type n="CFCPoint">{b3e42b54-b8f2-45d3-825d-747f82f244a0}</Type>
              <Type n="CFCPointList">{584effbc-813e-443a-bf78-ad9c8d49db41}</Type>
              <Type n="CFCRoutingConnection">{93c117eb-0884-403b-b01e-28b89f47e041}</Type>
              <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
              <Type n="CFCText">{72f2b13f-5349-4a8a-bbe6-2bccf3f42179}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="KindOfCall">{77f43dfe-ca6a-4869-828f-7609d8ed6ea6}</Type>
              <Type n="ProcessValueAccess">{88453c7d-d652-4a27-a1b0-a1953be49a5c}</Type>
              <Type n="SetReset">{24449d48-c96a-49c4-b9d1-a4ea34aedce3}</Type>
              <Type n="SetResetRef">{233bc97c-69fe-4d29-b40e-a9a9b854044e}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </CFC>
      </Implementation>
    </Action>
  </POU>
</TcPlcObject>