<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_MotorControlReverse" Id="{e3f6163d-999c-4c4f-bc04-2ed30004ff70}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_MotorControlReverse EXTENDS FB_MotorControl
VAR
	reverseButton		: Button;	// Scada Button reverse
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^(); //call base class 


//Button Forward is set in SCADA motor control station, but Client in PLC have to have acces too directly via a variable to work in Auto mode
IF reverseButton.IsPressed THEN

	ReverseOn(); 	// Switch Contactor On
	iDrive.WorkCounterOn();	//Start count work time	
				

ELSE

	ReverseOff();	// Switch Contactor Off 
	iDrive.WorkCounterOff();	//Stop count work time	
	
END_IF

// determine the state of the device and light the Taurus LED with the appropriate color
iDrive.TaurusState();]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{ae3fb759-2dd1-4395-b7cc-36f373dd76fb}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode  : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	iDrive		 : I_Drive;
			
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
]]></ST>
      </Implementation>
    </Method>
    <Method Name="ReverseOff" Id="{755b010d-844a-4604-9bcb-4be64e1215bf}">
      <Declaration><![CDATA[METHOD ReverseOff : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[iDrive.SwitchOff();]]></ST>
      </Implementation>
    </Method>
    <Method Name="ReverseOn" Id="{c76a633c-5fd6-4c8d-90e7-611a4362c596}">
      <Declaration><![CDATA[METHOD ReverseOn : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[iDrive.SwitchOn();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>