<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{5ce869a2-8876-462e-9766-a690c22efe4d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
	stWorkTime 				: ST_WorkTime;
	autoScadaButton			: Button_NO;
	forwardScadaButton		: Button_NO;
	reverseScadaButton		: Button_NO;
	stateScadaLed			: Led;
	autoScadaLed			: Led;
	supplyScadaLed			: Led;
	statusScadalabel		: Label;
	motorContactor 			: MotorContactor;
	motorTermFuse			: MotorTermFuse;
	motorWorkTime 			: WorkCounter;
	
	

	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
if 



motorWorkTime();
motorWorkTime.CheckState(forwardScadaButton);





]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>