<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{5ce869a2-8876-462e-9766-a690c22efe4d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
	mccMotor				: MccMotor;
	mccMotorP01				: MccMotor;

//	stWorkTime 				: ST_WorkTime;
//	autoScadaLed			: Led;
//	supplyScadaLed			: Led;
//	statusScadaLabel		: Label;
//	motorContactor 			: MotorContactor;
//	motorTermFuse			: MotorTermFuse;
//	autoScadaButton			: Button_NO;
//	forwardScadaButton		: Button_NO;
//	reverseScadaButton		: Button_NO;
//	stateTaurusLed			: TaurusLed(forwardScadaButton, motorTermFuse);
//	motorWorkTime 			: WorkCounter;
	
	
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[;
//mccMotor();
//mccMotorP01();







]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>