<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MotorWorkTime" Id="{bf300658-67ee-4a5c-88df-962f2b07572d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK MotorWorkTime
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>