<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Contactor" Id="{c060f755-e854-44d6-80a6-8e4dedcc8084}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Contactor
VAR
	_output AT%QX1.0: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="State" Id="{0e142a4b-cd3f-4ab7-9ab4-1784c7145a1f}">
      <Declaration><![CDATA[PROPERTY State : BOOL]]></Declaration>
      <Get Name="Get" Id="{a3074313-4226-4222-a590-1d86a6eb0a5e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[State := _output;]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{04cd2443-c326-4ff6-9a1d-095275924f65}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[_output := State;]]></ST>
        </Implementation>
      </Set>
    </Property>
  </POU>
</TcPlcObject>