<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Contactor" Id="{b6407330-2be5-4057-9fd3-32ede45bd45d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Contactor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="SwitchOff" Id="{1e79cbf9-deb8-4537-a369-af3cef9ed5b7}">
      <Declaration><![CDATA[METHOD SwitchOff : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="SwitchOn" Id="{8a2e985c-4aad-4eed-8852-369c45d86423}">
      <Declaration><![CDATA[METHOD SwitchOn : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>