<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Edit" Id="{dd182afd-7d10-410a-9d00-31674a3839a1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Edit
VAR
	_edit : T_MaxString;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Text" Id="{8c53d925-f5f0-4953-a30c-774f1d18bfb3}">
      <Declaration><![CDATA[PROPERTY Text : STRING]]></Declaration>
      <Get Name="Get" Id="{1f334f1c-bb17-48ab-974e-2444e2944be4}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Text := _edit;]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{ff9edd7d-ac20-4180-92ce-7533b13b0e7c}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Text := _edit;]]></ST>
        </Implementation>
      </Set>
    </Property>
  </POU>
</TcPlcObject>