<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Led" Id="{eee83838-3c2c-43ec-8b89-683878a85abd}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Led
VAR
	_state : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="State" Id="{e3a1b6cd-cb48-465d-b773-1a08ffdb9242}">
      <Declaration><![CDATA[PROPERTY State : BOOL]]></Declaration>
      <Get Name="Get" Id="{36c5ca79-529f-4892-bf03-3de869524f7e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[State := _state;]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{4324096c-7237-4c8f-8743-ad9168051b93}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[_state := State;]]></ST>
        </Implementation>
      </Set>
    </Property>
  </POU>
</TcPlcObject>