<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_DoubleContactor" Id="{cc7fc58b-d311-4e65-ad7d-7841037b2b38}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_DoubleContactor EXTENDS FB_Contactor IMPLEMENTS I_DriveDouble
VAR
	_outputReverse	AT%Q* : BOOL;	// Switch variable to start/stop Reverse psychical output
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="SwitchReverseOff" Id="{5505444f-14b2-4f81-9446-45e904c6b051}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD SwitchReverseOff : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_outputReverse := False;]]></ST>
      </Implementation>
    </Method>
    <Method Name="SwitchReverseOn" Id="{383937bc-a274-4aa8-97cc-b7751262242e}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD SwitchReverseOn : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_outputReverse := True;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>