<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Button_NO" Id="{6a31ca67-2efd-4a12-9b08-d9d7ccb5fe91}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Button_NO
VAR
	_input AT%M*	:BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IsActive" Id="{41f3700b-46e7-499b-ba0c-97c1c152ff2d}">
      <Declaration><![CDATA[PROPERTY IsActive : BOOL]]></Declaration>
      <Get Name="Get" Id="{4b486152-cfe4-4136-b2da-a2c8f67032f3}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IsActive:= _input;
]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>