<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TaurusLed" Id="{f6f49f3d-8a72-4f7a-b651-4716ce5ac1db}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TaurusLed
VAR
	_text AT%M* : T_MaxString;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Text" Id="{1aa88967-6225-4ffd-82b4-3b009d2bfb86}">
      <Declaration><![CDATA[PROPERTY Text : STRING]]></Declaration>
      <Get Name="Get" Id="{60d7d138-8c96-4745-b0e3-e36305ce1073}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Text := _text;]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{4611a705-c695-4abd-9093-7cf7b6a5ad8d}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[_text := Text;]]></ST>
        </Implementation>
      </Set>
    </Property>
  </POU>
</TcPlcObject>